/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as BooksBookIdRouteImport } from './routes/books/$bookId'
import { Route as AuthConfirmPasswordRouteImport } from './routes/auth/confirm-password'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmPasswordRoute = AuthConfirmPasswordRouteImport.update({
  id: '/auth/confirm-password',
  path: '/auth/confirm-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/confirm-password': typeof AuthConfirmPasswordRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/auth': typeof AuthIndexRoute
  '/books': typeof BooksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AuthedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/confirm-password': typeof AuthConfirmPasswordRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/auth': typeof AuthIndexRoute
  '/books': typeof BooksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AuthedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/confirm-password': typeof AuthConfirmPasswordRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/auth/': typeof AuthIndexRoute
  '/books/': typeof BooksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth/confirm-password'
    | '/books/$bookId'
    | '/auth'
    | '/books'
    | '/api/auth/$'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth/confirm-password'
    | '/books/$bookId'
    | '/auth'
    | '/books'
    | '/api/auth/$'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/auth/confirm-password'
    | '/books/$bookId'
    | '/auth/'
    | '/books/'
    | '/api/auth/$'
    | '/_authed/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthConfirmPasswordRoute: typeof AuthConfirmPasswordRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  AuthIndexRoute: typeof AuthIndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm-password': {
      id: '/auth/confirm-password'
      path: '/auth/confirm-password'
      fullPath: '/auth/confirm-password'
      preLoaderRoute: typeof AuthConfirmPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthConfirmPasswordRoute: AuthConfirmPasswordRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  AuthIndexRoute: AuthIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
