/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as MemberIndexRouteImport } from './routes/_member/index'
import { Route as AuthConfirmPasswordRouteImport } from './routes/auth/confirm-password'
import { Route as MemberAboutRouteImport } from './routes/_member/about'
import { Route as MemberBooksIndexRouteImport } from './routes/_member/books/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MemberBooksBookIdRouteImport } from './routes/_member/books/$bookId'
import { Route as AdminAdminReservationsIndexRouteImport } from './routes/_admin/admin/reservations/index'
import { Route as AdminAdminBooksIndexRouteImport } from './routes/_admin/admin/books/index'
import { Route as AdminAdminBooksCreateBookIndexRouteImport } from './routes/_admin/admin/books/create-book/index'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/_member/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmPasswordRoute = AuthConfirmPasswordRouteImport.update({
  id: '/auth/confirm-password',
  path: '/auth/confirm-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberAboutRoute = MemberAboutRouteImport.update({
  id: '/_member/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberBooksIndexRoute = MemberBooksIndexRouteImport.update({
  id: '/_member/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberBooksBookIdRoute = MemberBooksBookIdRouteImport.update({
  id: '/_member/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminReservationsIndexRoute =
  AdminAdminReservationsIndexRouteImport.update({
    id: '/admin/reservations/',
    path: '/admin/reservations/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAdminBooksIndexRoute = AdminAdminBooksIndexRouteImport.update({
  id: '/admin/books/',
  path: '/admin/books/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdminBooksCreateBookIndexRoute =
  AdminAdminBooksCreateBookIndexRouteImport.update({
    id: '/admin/books/create-book/',
    path: '/admin/books/create-book/',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MemberIndexRoute
  '/about': typeof MemberAboutRoute
  '/auth/confirm-password': typeof AuthConfirmPasswordRoute
  '/auth/': typeof AuthIndexRoute
  '/books/$bookId': typeof MemberBooksBookIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/books/': typeof MemberBooksIndexRoute
  '/admin/books/': typeof AdminAdminBooksIndexRoute
  '/admin/reservations/': typeof AdminAdminReservationsIndexRoute
  '/admin/books/create-book/': typeof AdminAdminBooksCreateBookIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MemberIndexRoute
  '/about': typeof MemberAboutRoute
  '/auth/confirm-password': typeof AuthConfirmPasswordRoute
  '/auth': typeof AuthIndexRoute
  '/books/$bookId': typeof MemberBooksBookIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AdminAdminIndexRoute
  '/books': typeof MemberBooksIndexRoute
  '/admin/books': typeof AdminAdminBooksIndexRoute
  '/admin/reservations': typeof AdminAdminReservationsIndexRoute
  '/admin/books/create-book': typeof AdminAdminBooksCreateBookIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_member/about': typeof MemberAboutRoute
  '/auth/confirm-password': typeof AuthConfirmPasswordRoute
  '/_member/': typeof MemberIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_member/books/$bookId': typeof MemberBooksBookIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_member/books/': typeof MemberBooksIndexRoute
  '/_admin/admin/books/': typeof AdminAdminBooksIndexRoute
  '/_admin/admin/reservations/': typeof AdminAdminReservationsIndexRoute
  '/_admin/admin/books/create-book/': typeof AdminAdminBooksCreateBookIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth/confirm-password'
    | '/auth/'
    | '/books/$bookId'
    | '/api/auth/$'
    | '/admin/'
    | '/books/'
    | '/admin/books/'
    | '/admin/reservations/'
    | '/admin/books/create-book/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth/confirm-password'
    | '/auth'
    | '/books/$bookId'
    | '/api/auth/$'
    | '/admin'
    | '/books'
    | '/admin/books'
    | '/admin/reservations'
    | '/admin/books/create-book'
  id:
    | '__root__'
    | '/_admin'
    | '/_member/about'
    | '/auth/confirm-password'
    | '/_member/'
    | '/auth/'
    | '/_member/books/$bookId'
    | '/api/auth/$'
    | '/_admin/admin/'
    | '/_member/books/'
    | '/_admin/admin/books/'
    | '/_admin/admin/reservations/'
    | '/_admin/admin/books/create-book/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  MemberAboutRoute: typeof MemberAboutRoute
  AuthConfirmPasswordRoute: typeof AuthConfirmPasswordRoute
  MemberIndexRoute: typeof MemberIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  MemberBooksBookIdRoute: typeof MemberBooksBookIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  MemberBooksIndexRoute: typeof MemberBooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member/': {
      id: '/_member/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm-password': {
      id: '/auth/confirm-password'
      path: '/auth/confirm-password'
      fullPath: '/auth/confirm-password'
      preLoaderRoute: typeof AuthConfirmPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member/about': {
      id: '/_member/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MemberAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member/books/': {
      id: '/_member/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof MemberBooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member/books/$bookId': {
      id: '/_member/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof MemberBooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/reservations/': {
      id: '/_admin/admin/reservations/'
      path: '/admin/reservations'
      fullPath: '/admin/reservations/'
      preLoaderRoute: typeof AdminAdminReservationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/books/': {
      id: '/_admin/admin/books/'
      path: '/admin/books'
      fullPath: '/admin/books/'
      preLoaderRoute: typeof AdminAdminBooksIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/admin/books/create-book/': {
      id: '/_admin/admin/books/create-book/'
      path: '/admin/books/create-book'
      fullPath: '/admin/books/create-book/'
      preLoaderRoute: typeof AdminAdminBooksCreateBookIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminBooksIndexRoute: typeof AdminAdminBooksIndexRoute
  AdminAdminReservationsIndexRoute: typeof AdminAdminReservationsIndexRoute
  AdminAdminBooksCreateBookIndexRoute: typeof AdminAdminBooksCreateBookIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminBooksIndexRoute: AdminAdminBooksIndexRoute,
  AdminAdminReservationsIndexRoute: AdminAdminReservationsIndexRoute,
  AdminAdminBooksCreateBookIndexRoute: AdminAdminBooksCreateBookIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  MemberAboutRoute: MemberAboutRoute,
  AuthConfirmPasswordRoute: AuthConfirmPasswordRoute,
  MemberIndexRoute: MemberIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  MemberBooksBookIdRoute: MemberBooksBookIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  MemberBooksIndexRoute: MemberBooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
