name: Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4

      - uses: voidzero-dev/setup-vp@v1
        with:
          cache: true

      - run: vp run build

      # - run: vp run test

      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      # - run: vp run deploy

  # deploy:
  #   runs-on: ubuntu-latest
  #   name: Deploy
  #   steps:
  #     - uses: cloudflare/wrangler-action@v3
  #       with:
